version: 0.2

phases:
  install:
    commands:
      - echo install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - ls
      - cd mingle
      - ls
      - cd script
  build:
    commands:
      - echo Build started on `date`
      - bash build
  post_build:
    commands:
      - echo Build completed on `date`
